# Generated by Django 5.1.6 on 2025-03-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='cafeApi.OrderItem', to='cafeApi.menuitem'),
        ),
    ]
