# Generated by Django 5.1.6 on 2025-03-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='production_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=6, null=True),
        ),
    ]
