# Generated by Django 5.1.6 on 2025-03-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafeApi", "0002_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.AddField(
            model_name="notification",
            name="kitchen_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cafeApi.kitchenstaff",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="waiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cafeApi.waiter",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
