# Generated by Django 5.1.6 on 2025-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0002_kitchenstaff_alter_order_status_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('being prepared', 'Being prepared'), ('ready for pick up', 'Ready for pick up'), ('delivered', 'Delivered'), ('paid for', 'Paid for')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('being prepared', 'Being prepared'), ('ready for pick up', 'Ready for pick up'), ('delivered', 'Delivered'), ('paid for', 'Paid for')], default='pending', max_length=20),
        ),
    ]
