# Generated by Django 5.1.5 on 2025-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
