# Generated by Django 5.1.6 on 2025-03-30 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0002_alter_menuitem_production_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='waiter_name',
        ),
        migrations.AddField(
            model_name='table',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafeApi.waiter'),
        ),
        migrations.AlterField(
            model_name='table',
            name='estimated_time',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('being prepared', 'Being prepared'), ('ready for pick up', 'Ready for pick up'), ('delivered', 'Delivered'), ('paid for', 'Paid for')], default='pending', max_length=20),
        ),
    ]
