# Generated by Django 5.1.6 on 2025-02-25 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafeApi", "0003_alter_order_status_alter_table_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("waiter_call", "Waiter Call"),
                            ("order_received", "Order Received"),
                            ("status_change", "Status Change"),
                            ("payment", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        choices=[
                            ("waiter", "Waiter"),
                            ("kitchen", "Kitchen Staff"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cafeApi.order",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cafeApi.table",
                    ),
                ),
            ],
        ),
    ]
