# Generated by Django 5.1.6 on 2025-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0003_remove_table_waiter_name_table_waiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='waiter',
        ),
        migrations.AddField(
            model_name='table',
            name='waiter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
