# Generated by Django 5.1.6 on 2025-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0003_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('being prepared', 'Being prepared'), ('ready for pick up', 'Ready for pick up'), ('delivered', 'Delivered'), ('paid for', 'Paid for')], default='Ok', max_length=20),
        ),
    ]
