# Generated by Django 5.1.6 on 2025-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0004_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
