# Generated by Django 5.1.6 on 2025-03-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0004_remove_table_waiter_table_waiter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='waiter_name',
        ),
        migrations.AddField(
            model_name='table',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='cafeApi.waiter'),
        ),
    ]
