# Generated by Django 5.1.6 on 2025-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0004_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('waiter_call', 'Waiter Call'), ('order_received', 'Order Received'), ('payment', 'Payment'), ('alert', 'Alert'), ('order_ready', 'Order_ready')], max_length=20),
        ),
    ]
