# Generated by Django 5.1.6 on 2025-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
