# Generated by Django 5.2 on 2025-04-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0005_remove_table_waiter_name_table_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('all orders received', 'All orders received'), ('alert', 'Alert')], default='pending', max_length=20),
        ),
    ]
