# Generated by Django 5.1.6 on 2025-03-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeApi.waiter')),
            ],
        ),
    ]
