# Generated by Django 5.1.6 on 2025-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0005_menuitem_calories_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
