# Generated by Django 5.1.6 on 2025-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0006_menuitem_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='availability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
