# Generated by Django 5.1.6 on 2025-02-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeApi', '0006_table_order_items_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='cafeApi.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cafeApi.table'),
            preserve_default=False,
        ),
    ]
